### PR TITLE
buttons

### PR DESCRIPTION
**Pull request by ghost**
added info about html buttons.

### CODE REVIEW

**Review by karinakozarova — CHANGES_REQUESTED** [review]
This is the difference between this element and buttons created with the input element.   -> could be rewritten to be more understandable

Add that you're using bootstrap because it hadn't been talked about so far. 

If you want to, you can add more text explanation, because now it is quite hard for understanding.

Everything else looks great to me. Good job  👍

**Comment by ghost** [comment]
@karinakozarova i added info about bootstrap and rewritten the topic you asked, hope it´s all good!!

**Review by karinakozarova — APPROVED** [review]
Thank you, very good 🎉 🎉

**Comment by nelsonic** [comment]
@edwardcodes if you have a question regarding a framework/library e.g: Bootstrap, please open an issue with a question. We don't use (Twitter) Bootstrap @dwyl because it does not *teach* people to understand CSS.

**Pull request merged**
